services:
  mysqldb:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userinfo
    container_name: "mysqldb"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      networks: 
        -mynetwork

  mypythonapp:
    build: ./
    container_name: mypyapp
    networks:
      - mynetwork
    volumes:
      - ./server.txt:/python/server.txt  #bind
    depends_on:
      mysqldb :  #jab tak mysqldb up na aajaye, mypythonapp ko hold pe rakho
        condition: service_healthy
    stdin_open: true
    tty: true 

networks:
  mynetwork: